global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus.localhost']

  - job_name: 'nestjs-tester'
    metrics_path: /mymetrics
    static_configs:
      - targets: ['api.localhost']